### ISSUE TITLE
tar: invalid magic and tar: short read

### ISSUE THREAD

**Issue by RyanDeamer** [digitalocean/netbox-docker#12]
Hi,

I'm getting this error can anyone help?

tar: invalid magic
tar: short read
ERROR: Service 'netbox' failed to build: The command '/bin/sh -c wget -q -O - "${URL}" | tar xz   && ln -s netbox* netbox' returned a non-zero code: 1

**Comment by miklasz** [comment]
you have to edit branch

`ARG BRANCH=v2.0.2
ARG URL=https://github.com/digitalocean/netbox/archive/$BRANCH.tar.gz
RUN wget -q -O - "${URL}" | tar xz \
  && ln -s netbox* netbox`

same in yaml file change version to v2.0.2

**Comment by RyanDeamer** [comment]
thanks all sorted

changed ARG BRANCH=2.0.3
added "COPY docker/nginx.conf /etc/netbox-nginx/nginx.conf" the docker file to
